/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class topicmodel_LDAKernel_LDAExecType */

#ifndef _Included_topicmodel_LDAKernel_LDAExecType
#define _Included_topicmodel_LDAKernel_LDAExecType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
