/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class topicmodel_LDAKernel */

#ifndef _Included_topicmodel_LDAKernel
#define _Included_topicmodel_LDAKernel
#ifdef __cplusplus
extern "C" {
#endif

void show_help();

/*
 * Class:     topicmodel_LDAKernel
 * Method:    calculateLDA
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_topicmodel_LDAKernel_calculateLDA
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
